# Generated by Django 5.0.6 on 2024-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_temurusers_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='temurusers',
            name='course',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
